// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: groupMsg.proto

package groupMsgpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupA string `protobuf:"bytes,1,opt,name=groupA,proto3" json:"groupA,omitempty"`
	GroupB string `protobuf:"bytes,2,opt,name=groupB,proto3" json:"groupB,omitempty"`
	GroupC string `protobuf:"bytes,3,opt,name=groupC,proto3" json:"groupC,omitempty"`
	TimeT  int64  `protobuf:"varint,4,opt,name=timeT,proto3" json:"timeT,omitempty"`
	MkA    string `protobuf:"bytes,5,opt,name=mkA,proto3" json:"mkA,omitempty"`
	MkB    string `protobuf:"bytes,6,opt,name=mkB,proto3" json:"mkB,omitempty"`
	MkC    string `protobuf:"bytes,7,opt,name=mkC,proto3" json:"mkC,omitempty"`
	RkA    string `protobuf:"bytes,8,opt,name=rkA,proto3" json:"rkA,omitempty"`
	RkB    string `protobuf:"bytes,9,opt,name=rkB,proto3" json:"rkB,omitempty"`
	RkC    string `protobuf:"bytes,10,opt,name=rkC,proto3" json:"rkC,omitempty"`
	PA     string `protobuf:"bytes,11,opt,name=pA,proto3" json:"pA,omitempty"`
	PB     string `protobuf:"bytes,12,opt,name=pB,proto3" json:"pB,omitempty"`
	PC     string `protobuf:"bytes,13,opt,name=pC,proto3" json:"pC,omitempty"`
}

func (x *GroupMsg) Reset() {
	*x = GroupMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_groupMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMsg) ProtoMessage() {}

func (x *GroupMsg) ProtoReflect() protoreflect.Message {
	mi := &file_groupMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMsg.ProtoReflect.Descriptor instead.
func (*GroupMsg) Descriptor() ([]byte, []int) {
	return file_groupMsg_proto_rawDescGZIP(), []int{0}
}

func (x *GroupMsg) GetGroupA() string {
	if x != nil {
		return x.GroupA
	}
	return ""
}

func (x *GroupMsg) GetGroupB() string {
	if x != nil {
		return x.GroupB
	}
	return ""
}

func (x *GroupMsg) GetGroupC() string {
	if x != nil {
		return x.GroupC
	}
	return ""
}

func (x *GroupMsg) GetTimeT() int64 {
	if x != nil {
		return x.TimeT
	}
	return 0
}

func (x *GroupMsg) GetMkA() string {
	if x != nil {
		return x.MkA
	}
	return ""
}

func (x *GroupMsg) GetMkB() string {
	if x != nil {
		return x.MkB
	}
	return ""
}

func (x *GroupMsg) GetMkC() string {
	if x != nil {
		return x.MkC
	}
	return ""
}

func (x *GroupMsg) GetRkA() string {
	if x != nil {
		return x.RkA
	}
	return ""
}

func (x *GroupMsg) GetRkB() string {
	if x != nil {
		return x.RkB
	}
	return ""
}

func (x *GroupMsg) GetRkC() string {
	if x != nil {
		return x.RkC
	}
	return ""
}

func (x *GroupMsg) GetPA() string {
	if x != nil {
		return x.PA
	}
	return ""
}

func (x *GroupMsg) GetPB() string {
	if x != nil {
		return x.PB
	}
	return ""
}

func (x *GroupMsg) GetPC() string {
	if x != nil {
		return x.PC
	}
	return ""
}

type GroupMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GroupMsgResponse) Reset() {
	*x = GroupMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_groupMsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMsgResponse) ProtoMessage() {}

func (x *GroupMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_groupMsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMsgResponse.ProtoReflect.Descriptor instead.
func (*GroupMsgResponse) Descriptor() ([]byte, []int) {
	return file_groupMsg_proto_rawDescGZIP(), []int{1}
}

var File_groupMsg_proto protoreflect.FileDescriptor

var file_groupMsg_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x73, 0x67, 0x70, 0x62, 0x22, 0x84, 0x02, 0x0a,
	0x08, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x41, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x41, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x43, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x43, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x54, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x54, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x6b, 0x41, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x6b, 0x41, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x6b, 0x42,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x6b, 0x42, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x6b, 0x43, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x6b, 0x43, 0x12, 0x10, 0x0a,
	0x03, 0x72, 0x6b, 0x41, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x6b, 0x41, 0x12,
	0x10, 0x0a, 0x03, 0x72, 0x6b, 0x42, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x6b,
	0x42, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6b, 0x43, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x72, 0x6b, 0x43, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x41, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x70, 0x41, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x42, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x70, 0x42, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x43, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x70, 0x43, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x59, 0x0a, 0x0e, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x4d, 0x73, 0x67, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x47, 0x0a, 0x0f, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x12, 0x14, 0x2e, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x4d, 0x73, 0x67, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d,
	0x73, 0x67, 0x1a, 0x1c, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x73, 0x67, 0x70, 0x62, 0x2e,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2e, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x73,
	0x67, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_groupMsg_proto_rawDescOnce sync.Once
	file_groupMsg_proto_rawDescData = file_groupMsg_proto_rawDesc
)

func file_groupMsg_proto_rawDescGZIP() []byte {
	file_groupMsg_proto_rawDescOnce.Do(func() {
		file_groupMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_groupMsg_proto_rawDescData)
	})
	return file_groupMsg_proto_rawDescData
}

var file_groupMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_groupMsg_proto_goTypes = []interface{}{
	(*GroupMsg)(nil),         // 0: groupMsgpb.GroupMsg
	(*GroupMsgResponse)(nil), // 1: groupMsgpb.GroupMsgResponse
}
var file_groupMsg_proto_depIdxs = []int32{
	0, // 0: groupMsgpb.GroupMsgHandle.GroupMsgReceive:input_type -> groupMsgpb.GroupMsg
	1, // 1: groupMsgpb.GroupMsgHandle.GroupMsgReceive:output_type -> groupMsgpb.GroupMsgResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_groupMsg_proto_init() }
func file_groupMsg_proto_init() {
	if File_groupMsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_groupMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_groupMsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_groupMsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_groupMsg_proto_goTypes,
		DependencyIndexes: file_groupMsg_proto_depIdxs,
		MessageInfos:      file_groupMsg_proto_msgTypes,
	}.Build()
	File_groupMsg_proto = out.File
	file_groupMsg_proto_rawDesc = nil
	file_groupMsg_proto_goTypes = nil
	file_groupMsg_proto_depIdxs = nil
}
