// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: groupMsg.proto

package groupMsgpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GroupMsgHandleClient is the client API for GroupMsgHandle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GroupMsgHandleClient interface {
	// Handles a received GroupMsg message
	GroupMsgReceive(ctx context.Context, in *GroupMsg, opts ...grpc.CallOption) (*GroupMsgResponse, error)
}

type groupMsgHandleClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupMsgHandleClient(cc grpc.ClientConnInterface) GroupMsgHandleClient {
	return &groupMsgHandleClient{cc}
}

func (c *groupMsgHandleClient) GroupMsgReceive(ctx context.Context, in *GroupMsg, opts ...grpc.CallOption) (*GroupMsgResponse, error) {
	out := new(GroupMsgResponse)
	err := c.cc.Invoke(ctx, "/groupMsgpb.GroupMsgHandle/GroupMsgReceive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupMsgHandleServer is the server API for GroupMsgHandle service.
// All implementations must embed UnimplementedGroupMsgHandleServer
// for forward compatibility
type GroupMsgHandleServer interface {
	// Handles a received GroupMsg message
	GroupMsgReceive(context.Context, *GroupMsg) (*GroupMsgResponse, error)
	mustEmbedUnimplementedGroupMsgHandleServer()
}

// UnimplementedGroupMsgHandleServer must be embedded to have forward compatible implementations.
type UnimplementedGroupMsgHandleServer struct {
}

func (UnimplementedGroupMsgHandleServer) GroupMsgReceive(context.Context, *GroupMsg) (*GroupMsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupMsgReceive not implemented")
}
func (UnimplementedGroupMsgHandleServer) mustEmbedUnimplementedGroupMsgHandleServer() {}

// UnsafeGroupMsgHandleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroupMsgHandleServer will
// result in compilation errors.
type UnsafeGroupMsgHandleServer interface {
	mustEmbedUnimplementedGroupMsgHandleServer()
}

func RegisterGroupMsgHandleServer(s grpc.ServiceRegistrar, srv GroupMsgHandleServer) {
	s.RegisterService(&GroupMsgHandle_ServiceDesc, srv)
}

func _GroupMsgHandle_GroupMsgReceive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupMsgHandleServer).GroupMsgReceive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/groupMsgpb.GroupMsgHandle/GroupMsgReceive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupMsgHandleServer).GroupMsgReceive(ctx, req.(*GroupMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// GroupMsgHandle_ServiceDesc is the grpc.ServiceDesc for GroupMsgHandle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GroupMsgHandle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "groupMsgpb.GroupMsgHandle",
	HandlerType: (*GroupMsgHandleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GroupMsgReceive",
			Handler:    _GroupMsgHandle_GroupMsgReceive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "groupMsg.proto",
}
