// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: tcPartSigMsg.proto

package tcPartSigMsgpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TcPartSigMsgHandleClient is the client API for TcPartSigMsgHandle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TcPartSigMsgHandleClient interface {
	// Handles a received tcPartSigMsg message
	TcPartSigMsgReceive(ctx context.Context, in *TcPartSigMsg, opts ...grpc.CallOption) (*TcPartSigMsgResponse, error)
}

type tcPartSigMsgHandleClient struct {
	cc grpc.ClientConnInterface
}

func NewTcPartSigMsgHandleClient(cc grpc.ClientConnInterface) TcPartSigMsgHandleClient {
	return &tcPartSigMsgHandleClient{cc}
}

func (c *tcPartSigMsgHandleClient) TcPartSigMsgReceive(ctx context.Context, in *TcPartSigMsg, opts ...grpc.CallOption) (*TcPartSigMsgResponse, error) {
	out := new(TcPartSigMsgResponse)
	err := c.cc.Invoke(ctx, "/tcPartSigMsgpb.TcPartSigMsgHandle/TcPartSigMsgReceive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TcPartSigMsgHandleServer is the server API for TcPartSigMsgHandle service.
// All implementations must embed UnimplementedTcPartSigMsgHandleServer
// for forward compatibility
type TcPartSigMsgHandleServer interface {
	// Handles a received tcPartSigMsg message
	TcPartSigMsgReceive(context.Context, *TcPartSigMsg) (*TcPartSigMsgResponse, error)
	mustEmbedUnimplementedTcPartSigMsgHandleServer()
}

// UnimplementedTcPartSigMsgHandleServer must be embedded to have forward compatible implementations.
type UnimplementedTcPartSigMsgHandleServer struct {
}

func (UnimplementedTcPartSigMsgHandleServer) TcPartSigMsgReceive(context.Context, *TcPartSigMsg) (*TcPartSigMsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TcPartSigMsgReceive not implemented")
}
func (UnimplementedTcPartSigMsgHandleServer) mustEmbedUnimplementedTcPartSigMsgHandleServer() {}

// UnsafeTcPartSigMsgHandleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TcPartSigMsgHandleServer will
// result in compilation errors.
type UnsafeTcPartSigMsgHandleServer interface {
	mustEmbedUnimplementedTcPartSigMsgHandleServer()
}

func RegisterTcPartSigMsgHandleServer(s grpc.ServiceRegistrar, srv TcPartSigMsgHandleServer) {
	s.RegisterService(&TcPartSigMsgHandle_ServiceDesc, srv)
}

func _TcPartSigMsgHandle_TcPartSigMsgReceive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TcPartSigMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TcPartSigMsgHandleServer).TcPartSigMsgReceive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tcPartSigMsgpb.TcPartSigMsgHandle/TcPartSigMsgReceive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TcPartSigMsgHandleServer).TcPartSigMsgReceive(ctx, req.(*TcPartSigMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// TcPartSigMsgHandle_ServiceDesc is the grpc.ServiceDesc for TcPartSigMsgHandle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TcPartSigMsgHandle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tcPartSigMsgpb.TcPartSigMsgHandle",
	HandlerType: (*TcPartSigMsgHandleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TcPartSigMsgReceive",
			Handler:    _TcPartSigMsgHandle_TcPartSigMsgReceive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tcPartSigMsg.proto",
}
