// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: tcPartSigMsg.proto

package tcPartSigMsgpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type TcPartSigMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Round int64  `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Id    int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Sig   string `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"`
}

func (x *TcPartSigMsg) Reset() {
	*x = TcPartSigMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tcPartSigMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TcPartSigMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcPartSigMsg) ProtoMessage() {}

func (x *TcPartSigMsg) ProtoReflect() protoreflect.Message {
	mi := &file_tcPartSigMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcPartSigMsg.ProtoReflect.Descriptor instead.
func (*TcPartSigMsg) Descriptor() ([]byte, []int) {
	return file_tcPartSigMsg_proto_rawDescGZIP(), []int{0}
}

func (x *TcPartSigMsg) GetRound() int64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *TcPartSigMsg) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TcPartSigMsg) GetSig() string {
	if x != nil {
		return x.Sig
	}
	return ""
}

type TcPartSigMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TcPartSigMsgResponse) Reset() {
	*x = TcPartSigMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tcPartSigMsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TcPartSigMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcPartSigMsgResponse) ProtoMessage() {}

func (x *TcPartSigMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tcPartSigMsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcPartSigMsgResponse.ProtoReflect.Descriptor instead.
func (*TcPartSigMsgResponse) Descriptor() ([]byte, []int) {
	return file_tcPartSigMsg_proto_rawDescGZIP(), []int{1}
}

var File_tcPartSigMsg_proto protoreflect.FileDescriptor

var file_tcPartSigMsg_proto_rawDesc = []byte{
	0x0a, 0x12, 0x74, 0x63, 0x50, 0x61, 0x72, 0x74, 0x53, 0x69, 0x67, 0x4d, 0x73, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x74, 0x63, 0x50, 0x61, 0x72, 0x74, 0x53, 0x69, 0x67, 0x4d,
	0x73, 0x67, 0x70, 0x62, 0x22, 0x46, 0x0a, 0x0c, 0x54, 0x63, 0x50, 0x61, 0x72, 0x74, 0x53, 0x69,
	0x67, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x69, 0x67, 0x22, 0x16, 0x0a, 0x14,
	0x54, 0x63, 0x50, 0x61, 0x72, 0x74, 0x53, 0x69, 0x67, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0x71, 0x0a, 0x12, 0x54, 0x63, 0x50, 0x61, 0x72, 0x74, 0x53, 0x69,
	0x67, 0x4d, 0x73, 0x67, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x5b, 0x0a, 0x13, 0x54, 0x63,
	0x50, 0x61, 0x72, 0x74, 0x53, 0x69, 0x67, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x12, 0x1c, 0x2e, 0x74, 0x63, 0x50, 0x61, 0x72, 0x74, 0x53, 0x69, 0x67, 0x4d, 0x73, 0x67,
	0x70, 0x62, 0x2e, 0x54, 0x63, 0x50, 0x61, 0x72, 0x74, 0x53, 0x69, 0x67, 0x4d, 0x73, 0x67, 0x1a,
	0x24, 0x2e, 0x74, 0x63, 0x50, 0x61, 0x72, 0x74, 0x53, 0x69, 0x67, 0x4d, 0x73, 0x67, 0x70, 0x62,
	0x2e, 0x54, 0x63, 0x50, 0x61, 0x72, 0x74, 0x53, 0x69, 0x67, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2e, 0x2f, 0x74, 0x63,
	0x50, 0x61, 0x72, 0x74, 0x53, 0x69, 0x67, 0x4d, 0x73, 0x67, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tcPartSigMsg_proto_rawDescOnce sync.Once
	file_tcPartSigMsg_proto_rawDescData = file_tcPartSigMsg_proto_rawDesc
)

func file_tcPartSigMsg_proto_rawDescGZIP() []byte {
	file_tcPartSigMsg_proto_rawDescOnce.Do(func() {
		file_tcPartSigMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_tcPartSigMsg_proto_rawDescData)
	})
	return file_tcPartSigMsg_proto_rawDescData
}

var file_tcPartSigMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tcPartSigMsg_proto_goTypes = []interface{}{
	(*TcPartSigMsg)(nil),         // 0: tcPartSigMsgpb.TcPartSigMsg
	(*TcPartSigMsgResponse)(nil), // 1: tcPartSigMsgpb.TcPartSigMsgResponse
}
var file_tcPartSigMsg_proto_depIdxs = []int32{
	0, // 0: tcPartSigMsgpb.TcPartSigMsgHandle.TcPartSigMsgReceive:input_type -> tcPartSigMsgpb.TcPartSigMsg
	1, // 1: tcPartSigMsgpb.TcPartSigMsgHandle.TcPartSigMsgReceive:output_type -> tcPartSigMsgpb.TcPartSigMsgResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tcPartSigMsg_proto_init() }
func file_tcPartSigMsg_proto_init() {
	if File_tcPartSigMsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tcPartSigMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TcPartSigMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tcPartSigMsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TcPartSigMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tcPartSigMsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tcPartSigMsg_proto_goTypes,
		DependencyIndexes: file_tcPartSigMsg_proto_depIdxs,
		MessageInfos:      file_tcPartSigMsg_proto_msgTypes,
	}.Build()
	File_tcPartSigMsg_proto = out.File
	file_tcPartSigMsg_proto_rawDesc = nil
	file_tcPartSigMsg_proto_goTypes = nil
	file_tcPartSigMsg_proto_depIdxs = nil
}
