// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: tcMsg.proto

package tcMsgpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type TcMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Round     int64  `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	MaskedMsg string `protobuf:"bytes,2,opt,name=maskedMsg,proto3" json:"maskedMsg,omitempty"`
	HA        string `protobuf:"bytes,3,opt,name=h_a,json=hA,proto3" json:"h_a,omitempty"`
	HB        string `protobuf:"bytes,4,opt,name=h_b,json=hB,proto3" json:"h_b,omitempty"`
	HC        string `protobuf:"bytes,5,opt,name=h_c,json=hC,proto3" json:"h_c,omitempty"`
	MkA       string `protobuf:"bytes,6,opt,name=Mk_a,json=MkA,proto3" json:"Mk_a,omitempty"`
	MkB       string `protobuf:"bytes,7,opt,name=Mk_b,json=MkB,proto3" json:"Mk_b,omitempty"`
	MkC       string `protobuf:"bytes,8,opt,name=Mk_c,json=MkC,proto3" json:"Mk_c,omitempty"`
	A1A       string `protobuf:"bytes,9,opt,name=a1_a,json=a1A,proto3" json:"a1_a,omitempty"`
	A1B       string `protobuf:"bytes,10,opt,name=a1_b,json=a1B,proto3" json:"a1_b,omitempty"`
	A1C       string `protobuf:"bytes,11,opt,name=a1_c,json=a1C,proto3" json:"a1_c,omitempty"`
	A2A       string `protobuf:"bytes,12,opt,name=a2_a,json=a2A,proto3" json:"a2_a,omitempty"`
	A2B       string `protobuf:"bytes,13,opt,name=a2_b,json=a2B,proto3" json:"a2_b,omitempty"`
	A2C       string `protobuf:"bytes,14,opt,name=a2_c,json=a2C,proto3" json:"a2_c,omitempty"`
	Z         string `protobuf:"bytes,15,opt,name=z,proto3" json:"z,omitempty"`
	Id        int64  `protobuf:"varint,16,opt,name=id,proto3" json:"id,omitempty"`
	Sig       string `protobuf:"bytes,17,opt,name=sig,proto3" json:"sig,omitempty"`
}

func (x *TcMsg) Reset() {
	*x = TcMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tcMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TcMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcMsg) ProtoMessage() {}

func (x *TcMsg) ProtoReflect() protoreflect.Message {
	mi := &file_tcMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcMsg.ProtoReflect.Descriptor instead.
func (*TcMsg) Descriptor() ([]byte, []int) {
	return file_tcMsg_proto_rawDescGZIP(), []int{0}
}

func (x *TcMsg) GetRound() int64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *TcMsg) GetMaskedMsg() string {
	if x != nil {
		return x.MaskedMsg
	}
	return ""
}

func (x *TcMsg) GetHA() string {
	if x != nil {
		return x.HA
	}
	return ""
}

func (x *TcMsg) GetHB() string {
	if x != nil {
		return x.HB
	}
	return ""
}

func (x *TcMsg) GetHC() string {
	if x != nil {
		return x.HC
	}
	return ""
}

func (x *TcMsg) GetMkA() string {
	if x != nil {
		return x.MkA
	}
	return ""
}

func (x *TcMsg) GetMkB() string {
	if x != nil {
		return x.MkB
	}
	return ""
}

func (x *TcMsg) GetMkC() string {
	if x != nil {
		return x.MkC
	}
	return ""
}

func (x *TcMsg) GetA1A() string {
	if x != nil {
		return x.A1A
	}
	return ""
}

func (x *TcMsg) GetA1B() string {
	if x != nil {
		return x.A1B
	}
	return ""
}

func (x *TcMsg) GetA1C() string {
	if x != nil {
		return x.A1C
	}
	return ""
}

func (x *TcMsg) GetA2A() string {
	if x != nil {
		return x.A2A
	}
	return ""
}

func (x *TcMsg) GetA2B() string {
	if x != nil {
		return x.A2B
	}
	return ""
}

func (x *TcMsg) GetA2C() string {
	if x != nil {
		return x.A2C
	}
	return ""
}

func (x *TcMsg) GetZ() string {
	if x != nil {
		return x.Z
	}
	return ""
}

func (x *TcMsg) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TcMsg) GetSig() string {
	if x != nil {
		return x.Sig
	}
	return ""
}

type TcMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TcMsgResponse) Reset() {
	*x = TcMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tcMsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TcMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcMsgResponse) ProtoMessage() {}

func (x *TcMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tcMsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcMsgResponse.ProtoReflect.Descriptor instead.
func (*TcMsgResponse) Descriptor() ([]byte, []int) {
	return file_tcMsg_proto_rawDescGZIP(), []int{1}
}

var File_tcMsg_proto protoreflect.FileDescriptor

var file_tcMsg_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x63, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x74,
	0x63, 0x4d, 0x73, 0x67, 0x70, 0x62, 0x22, 0xc9, 0x02, 0x0a, 0x05, 0x54, 0x63, 0x4d, 0x73, 0x67,
	0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x73, 0x6b, 0x65, 0x64,
	0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x61, 0x73, 0x6b, 0x65,
	0x64, 0x4d, 0x73, 0x67, 0x12, 0x0f, 0x0a, 0x03, 0x68, 0x5f, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x68, 0x41, 0x12, 0x0f, 0x0a, 0x03, 0x68, 0x5f, 0x62, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x68, 0x42, 0x12, 0x0f, 0x0a, 0x03, 0x68, 0x5f, 0x63, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x68, 0x43, 0x12, 0x11, 0x0a, 0x04, 0x4d, 0x6b, 0x5f, 0x61, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x6b, 0x41, 0x12, 0x11, 0x0a, 0x04, 0x4d, 0x6b,
	0x5f, 0x62, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x6b, 0x42, 0x12, 0x11, 0x0a,
	0x04, 0x4d, 0x6b, 0x5f, 0x63, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x6b, 0x43,
	0x12, 0x11, 0x0a, 0x04, 0x61, 0x31, 0x5f, 0x61, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x61, 0x31, 0x41, 0x12, 0x11, 0x0a, 0x04, 0x61, 0x31, 0x5f, 0x62, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x61, 0x31, 0x42, 0x12, 0x11, 0x0a, 0x04, 0x61, 0x31, 0x5f, 0x63, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x31, 0x43, 0x12, 0x11, 0x0a, 0x04, 0x61, 0x32, 0x5f,
	0x61, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x32, 0x41, 0x12, 0x11, 0x0a, 0x04,
	0x61, 0x32, 0x5f, 0x62, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x32, 0x42, 0x12,
	0x11, 0x0a, 0x04, 0x61, 0x32, 0x5f, 0x63, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61,
	0x32, 0x43, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x7a,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x10, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x67, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73,
	0x69, 0x67, 0x22, 0x0f, 0x0a, 0x0d, 0x54, 0x63, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x32, 0x47, 0x0a, 0x0b, 0x54, 0x63, 0x4d, 0x73, 0x67, 0x48, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x12, 0x38, 0x0a, 0x0c, 0x54, 0x63, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x12, 0x0e, 0x2e, 0x74, 0x63, 0x4d, 0x73, 0x67, 0x70, 0x62, 0x2e, 0x54, 0x63, 0x4d,
	0x73, 0x67, 0x1a, 0x16, 0x2e, 0x74, 0x63, 0x4d, 0x73, 0x67, 0x70, 0x62, 0x2e, 0x54, 0x63, 0x4d,
	0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a,
	0x2e, 0x2e, 0x2f, 0x74, 0x63, 0x4d, 0x73, 0x67, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_tcMsg_proto_rawDescOnce sync.Once
	file_tcMsg_proto_rawDescData = file_tcMsg_proto_rawDesc
)

func file_tcMsg_proto_rawDescGZIP() []byte {
	file_tcMsg_proto_rawDescOnce.Do(func() {
		file_tcMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_tcMsg_proto_rawDescData)
	})
	return file_tcMsg_proto_rawDescData
}

var file_tcMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tcMsg_proto_goTypes = []interface{}{
	(*TcMsg)(nil),         // 0: tcMsgpb.TcMsg
	(*TcMsgResponse)(nil), // 1: tcMsgpb.TcMsgResponse
}
var file_tcMsg_proto_depIdxs = []int32{
	0, // 0: tcMsgpb.TcMsgHandle.TcMsgReceive:input_type -> tcMsgpb.TcMsg
	1, // 1: tcMsgpb.TcMsgHandle.TcMsgReceive:output_type -> tcMsgpb.TcMsgResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tcMsg_proto_init() }
func file_tcMsg_proto_init() {
	if File_tcMsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tcMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TcMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tcMsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TcMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tcMsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tcMsg_proto_goTypes,
		DependencyIndexes: file_tcMsg_proto_depIdxs,
		MessageInfos:      file_tcMsg_proto_msgTypes,
	}.Build()
	File_tcMsg_proto = out.File
	file_tcMsg_proto_rawDesc = nil
	file_tcMsg_proto_goTypes = nil
	file_tcMsg_proto_depIdxs = nil
}
