// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: tcMsg.proto

package tcMsgpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TcMsgHandleClient is the client API for TcMsgHandle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TcMsgHandleClient interface {
	// Handles a received tcMsg message
	TcMsgReceive(ctx context.Context, in *TcMsg, opts ...grpc.CallOption) (*TcMsgResponse, error)
}

type tcMsgHandleClient struct {
	cc grpc.ClientConnInterface
}

func NewTcMsgHandleClient(cc grpc.ClientConnInterface) TcMsgHandleClient {
	return &tcMsgHandleClient{cc}
}

func (c *tcMsgHandleClient) TcMsgReceive(ctx context.Context, in *TcMsg, opts ...grpc.CallOption) (*TcMsgResponse, error) {
	out := new(TcMsgResponse)
	err := c.cc.Invoke(ctx, "/tcMsgpb.TcMsgHandle/TcMsgReceive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TcMsgHandleServer is the server API for TcMsgHandle service.
// All implementations must embed UnimplementedTcMsgHandleServer
// for forward compatibility
type TcMsgHandleServer interface {
	// Handles a received tcMsg message
	TcMsgReceive(context.Context, *TcMsg) (*TcMsgResponse, error)
	mustEmbedUnimplementedTcMsgHandleServer()
}

// UnimplementedTcMsgHandleServer must be embedded to have forward compatible implementations.
type UnimplementedTcMsgHandleServer struct {
}

func (UnimplementedTcMsgHandleServer) TcMsgReceive(context.Context, *TcMsg) (*TcMsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TcMsgReceive not implemented")
}
func (UnimplementedTcMsgHandleServer) mustEmbedUnimplementedTcMsgHandleServer() {}

// UnsafeTcMsgHandleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TcMsgHandleServer will
// result in compilation errors.
type UnsafeTcMsgHandleServer interface {
	mustEmbedUnimplementedTcMsgHandleServer()
}

func RegisterTcMsgHandleServer(s grpc.ServiceRegistrar, srv TcMsgHandleServer) {
	s.RegisterService(&TcMsgHandle_ServiceDesc, srv)
}

func _TcMsgHandle_TcMsgReceive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TcMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TcMsgHandleServer).TcMsgReceive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tcMsgpb.TcMsgHandle/TcMsgReceive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TcMsgHandleServer).TcMsgReceive(ctx, req.(*TcMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// TcMsgHandle_ServiceDesc is the grpc.ServiceDesc for TcMsgHandle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TcMsgHandle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tcMsgpb.TcMsgHandle",
	HandlerType: (*TcMsgHandleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TcMsgReceive",
			Handler:    _TcMsgHandle_TcMsgReceive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tcMsg.proto",
}
