// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: errSetupMsg.proto

package errSetupMsgpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrSetupMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SecretShareI  int64    `protobuf:"varint,2,opt,name=SecretShareI,proto3" json:"SecretShareI,omitempty"`
	SecretShareV  string   `protobuf:"bytes,3,opt,name=SecretShareV,proto3" json:"SecretShareV,omitempty"`
	GlobalPubKey  string   `protobuf:"bytes,4,opt,name=GlobalPubKey,proto3" json:"GlobalPubKey,omitempty"`
	PubPolyBase   string   `protobuf:"bytes,5,opt,name=pubPolyBase,proto3" json:"pubPolyBase,omitempty"`
	PubPolyCommit []string `protobuf:"bytes,6,rep,name=pubPolyCommit,proto3" json:"pubPolyCommit,omitempty"`
}

func (x *ErrSetupMsg) Reset() {
	*x = ErrSetupMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_errSetupMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrSetupMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrSetupMsg) ProtoMessage() {}

func (x *ErrSetupMsg) ProtoReflect() protoreflect.Message {
	mi := &file_errSetupMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrSetupMsg.ProtoReflect.Descriptor instead.
func (*ErrSetupMsg) Descriptor() ([]byte, []int) {
	return file_errSetupMsg_proto_rawDescGZIP(), []int{0}
}

func (x *ErrSetupMsg) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ErrSetupMsg) GetSecretShareI() int64 {
	if x != nil {
		return x.SecretShareI
	}
	return 0
}

func (x *ErrSetupMsg) GetSecretShareV() string {
	if x != nil {
		return x.SecretShareV
	}
	return ""
}

func (x *ErrSetupMsg) GetGlobalPubKey() string {
	if x != nil {
		return x.GlobalPubKey
	}
	return ""
}

func (x *ErrSetupMsg) GetPubPolyBase() string {
	if x != nil {
		return x.PubPolyBase
	}
	return ""
}

func (x *ErrSetupMsg) GetPubPolyCommit() []string {
	if x != nil {
		return x.PubPolyCommit
	}
	return nil
}

type ErrSetupMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ErrSetupMsgResponse) Reset() {
	*x = ErrSetupMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_errSetupMsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrSetupMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrSetupMsgResponse) ProtoMessage() {}

func (x *ErrSetupMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_errSetupMsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrSetupMsgResponse.ProtoReflect.Descriptor instead.
func (*ErrSetupMsgResponse) Descriptor() ([]byte, []int) {
	return file_errSetupMsg_proto_rawDescGZIP(), []int{1}
}

var File_errSetupMsg_proto protoreflect.FileDescriptor

var file_errSetupMsg_proto_rawDesc = []byte{
	0x0a, 0x11, 0x65, 0x72, 0x72, 0x53, 0x65, 0x74, 0x75, 0x70, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x65, 0x72, 0x72, 0x53, 0x65, 0x74, 0x75, 0x70, 0x4d, 0x73, 0x67,
	0x70, 0x62, 0x22, 0xd1, 0x01, 0x0a, 0x0b, 0x45, 0x72, 0x72, 0x53, 0x65, 0x74, 0x75, 0x70, 0x4d,
	0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x53, 0x68, 0x61, 0x72,
	0x65, 0x49, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x53, 0x68, 0x61, 0x72, 0x65, 0x49, 0x12, 0x22, 0x0a, 0x0c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x53, 0x68, 0x61, 0x72, 0x65, 0x56, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x53, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x53, 0x68, 0x61, 0x72, 0x65, 0x56, 0x12, 0x22, 0x0a, 0x0c, 0x47, 0x6c,
	0x6f, 0x62, 0x61, 0x6c, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x20,
	0x0a, 0x0b, 0x70, 0x75, 0x62, 0x50, 0x6f, 0x6c, 0x79, 0x42, 0x61, 0x73, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x75, 0x62, 0x50, 0x6f, 0x6c, 0x79, 0x42, 0x61, 0x73, 0x65,
	0x12, 0x24, 0x0a, 0x0d, 0x70, 0x75, 0x62, 0x50, 0x6f, 0x6c, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x75, 0x62, 0x50, 0x6f, 0x6c, 0x79,
	0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x45, 0x72, 0x72, 0x53, 0x65, 0x74,
	0x75, 0x70, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x6b, 0x0a,
	0x11, 0x45, 0x72, 0x72, 0x53, 0x65, 0x74, 0x75, 0x70, 0x4d, 0x73, 0x67, 0x48, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x12, 0x56, 0x0a, 0x12, 0x45, 0x72, 0x72, 0x53, 0x65, 0x74, 0x75, 0x70, 0x4d, 0x73,
	0x67, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x12, 0x1a, 0x2e, 0x65, 0x72, 0x72, 0x53, 0x65,
	0x74, 0x75, 0x70, 0x4d, 0x73, 0x67, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x53, 0x65, 0x74, 0x75,
	0x70, 0x4d, 0x73, 0x67, 0x1a, 0x22, 0x2e, 0x65, 0x72, 0x72, 0x53, 0x65, 0x74, 0x75, 0x70, 0x4d,
	0x73, 0x67, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x53, 0x65, 0x74, 0x75, 0x70, 0x4d, 0x73, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2e,
	0x2f, 0x65, 0x72, 0x72, 0x53, 0x65, 0x74, 0x75, 0x70, 0x4d, 0x73, 0x67, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_errSetupMsg_proto_rawDescOnce sync.Once
	file_errSetupMsg_proto_rawDescData = file_errSetupMsg_proto_rawDesc
)

func file_errSetupMsg_proto_rawDescGZIP() []byte {
	file_errSetupMsg_proto_rawDescOnce.Do(func() {
		file_errSetupMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_errSetupMsg_proto_rawDescData)
	})
	return file_errSetupMsg_proto_rawDescData
}

var file_errSetupMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_errSetupMsg_proto_goTypes = []interface{}{
	(*ErrSetupMsg)(nil),         // 0: errSetupMsgpb.ErrSetupMsg
	(*ErrSetupMsgResponse)(nil), // 1: errSetupMsgpb.ErrSetupMsgResponse
}
var file_errSetupMsg_proto_depIdxs = []int32{
	0, // 0: errSetupMsgpb.ErrSetupMsgHandle.ErrSetupMsgReceive:input_type -> errSetupMsgpb.ErrSetupMsg
	1, // 1: errSetupMsgpb.ErrSetupMsgHandle.ErrSetupMsgReceive:output_type -> errSetupMsgpb.ErrSetupMsgResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errSetupMsg_proto_init() }
func file_errSetupMsg_proto_init() {
	if File_errSetupMsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_errSetupMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrSetupMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_errSetupMsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrSetupMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_errSetupMsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_errSetupMsg_proto_goTypes,
		DependencyIndexes: file_errSetupMsg_proto_depIdxs,
		MessageInfos:      file_errSetupMsg_proto_msgTypes,
	}.Build()
	File_errSetupMsg_proto = out.File
	file_errSetupMsg_proto_rawDesc = nil
	file_errSetupMsg_proto_goTypes = nil
	file_errSetupMsg_proto_depIdxs = nil
}
