// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: blankReplyMsg.proto

package blankReplyMsgpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlankReplyMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequireRound int64  `protobuf:"varint,1,opt,name=requireRound,proto3" json:"requireRound,omitempty"`
	MaskedMsg    string `protobuf:"bytes,2,opt,name=maskedMsg,proto3" json:"maskedMsg,omitempty"`
	HA           string `protobuf:"bytes,3,opt,name=HA,proto3" json:"HA,omitempty"`
	HB           string `protobuf:"bytes,4,opt,name=HB,proto3" json:"HB,omitempty"`
	HC           string `protobuf:"bytes,5,opt,name=HC,proto3" json:"HC,omitempty"`
	CompleteSig  string `protobuf:"bytes,6,opt,name=completeSig,proto3" json:"completeSig,omitempty"`
}

func (x *BlankReplyMsg) Reset() {
	*x = BlankReplyMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blankReplyMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlankReplyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlankReplyMsg) ProtoMessage() {}

func (x *BlankReplyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_blankReplyMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlankReplyMsg.ProtoReflect.Descriptor instead.
func (*BlankReplyMsg) Descriptor() ([]byte, []int) {
	return file_blankReplyMsg_proto_rawDescGZIP(), []int{0}
}

func (x *BlankReplyMsg) GetRequireRound() int64 {
	if x != nil {
		return x.RequireRound
	}
	return 0
}

func (x *BlankReplyMsg) GetMaskedMsg() string {
	if x != nil {
		return x.MaskedMsg
	}
	return ""
}

func (x *BlankReplyMsg) GetHA() string {
	if x != nil {
		return x.HA
	}
	return ""
}

func (x *BlankReplyMsg) GetHB() string {
	if x != nil {
		return x.HB
	}
	return ""
}

func (x *BlankReplyMsg) GetHC() string {
	if x != nil {
		return x.HC
	}
	return ""
}

func (x *BlankReplyMsg) GetCompleteSig() string {
	if x != nil {
		return x.CompleteSig
	}
	return ""
}

type BlankReplyMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BlankReplyMsgResponse) Reset() {
	*x = BlankReplyMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blankReplyMsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlankReplyMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlankReplyMsgResponse) ProtoMessage() {}

func (x *BlankReplyMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blankReplyMsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlankReplyMsgResponse.ProtoReflect.Descriptor instead.
func (*BlankReplyMsgResponse) Descriptor() ([]byte, []int) {
	return file_blankReplyMsg_proto_rawDescGZIP(), []int{1}
}

var File_blankReplyMsg_proto protoreflect.FileDescriptor

var file_blankReplyMsg_proto_rawDesc = []byte{
	0x0a, 0x13, 0x62, 0x6c, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4d, 0x73, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x62, 0x6c, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x4d, 0x73, 0x67, 0x70, 0x62, 0x22, 0xa3, 0x01, 0x0a, 0x0d, 0x42, 0x6c, 0x61, 0x6e, 0x6b,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x4d, 0x73, 0x67, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c,
	0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x6d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x4d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x48, 0x41,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x48, 0x41, 0x12, 0x0e, 0x0a, 0x02, 0x48, 0x42,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x48, 0x42, 0x12, 0x0e, 0x0a, 0x02, 0x48, 0x43,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x48, 0x43, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x69, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x69, 0x67, 0x22, 0x17, 0x0a, 0x15,
	0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x77, 0x0a, 0x13, 0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x4d, 0x73, 0x67, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x60, 0x0a, 0x14,
	0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x12, 0x1e, 0x2e, 0x62, 0x6c, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x4d, 0x73, 0x67, 0x70, 0x62, 0x2e, 0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x4d, 0x73, 0x67, 0x1a, 0x26, 0x2e, 0x62, 0x6c, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x4d, 0x73, 0x67, 0x70, 0x62, 0x2e, 0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x14,
	0x5a, 0x12, 0x2e, 0x2e, 0x2f, 0x62, 0x6c, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4d,
	0x73, 0x67, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blankReplyMsg_proto_rawDescOnce sync.Once
	file_blankReplyMsg_proto_rawDescData = file_blankReplyMsg_proto_rawDesc
)

func file_blankReplyMsg_proto_rawDescGZIP() []byte {
	file_blankReplyMsg_proto_rawDescOnce.Do(func() {
		file_blankReplyMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_blankReplyMsg_proto_rawDescData)
	})
	return file_blankReplyMsg_proto_rawDescData
}

var file_blankReplyMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_blankReplyMsg_proto_goTypes = []interface{}{
	(*BlankReplyMsg)(nil),         // 0: blankReplyMsgpb.BlankReplyMsg
	(*BlankReplyMsgResponse)(nil), // 1: blankReplyMsgpb.BlankReplyMsgResponse
}
var file_blankReplyMsg_proto_depIdxs = []int32{
	0, // 0: blankReplyMsgpb.BlankReplyMsgHandle.BlankReplyMsgReceive:input_type -> blankReplyMsgpb.BlankReplyMsg
	1, // 1: blankReplyMsgpb.BlankReplyMsgHandle.BlankReplyMsgReceive:output_type -> blankReplyMsgpb.BlankReplyMsgResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blankReplyMsg_proto_init() }
func file_blankReplyMsg_proto_init() {
	if File_blankReplyMsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_blankReplyMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlankReplyMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blankReplyMsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlankReplyMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blankReplyMsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blankReplyMsg_proto_goTypes,
		DependencyIndexes: file_blankReplyMsg_proto_depIdxs,
		MessageInfos:      file_blankReplyMsg_proto_msgTypes,
	}.Build()
	File_blankReplyMsg_proto = out.File
	file_blankReplyMsg_proto_rawDesc = nil
	file_blankReplyMsg_proto_goTypes = nil
	file_blankReplyMsg_proto_depIdxs = nil
}
