// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: tcFullSigMsg.proto

package tcFullSigMsgpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TcFullSigMsgHandleClient is the client API for TcFullSigMsgHandle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TcFullSigMsgHandleClient interface {
	// Handles a received tcFullSigMsg message
	TcFullSigMsgReceive(ctx context.Context, in *TcFullSigMsg, opts ...grpc.CallOption) (*TcFullSigMsgResponse, error)
}

type tcFullSigMsgHandleClient struct {
	cc grpc.ClientConnInterface
}

func NewTcFullSigMsgHandleClient(cc grpc.ClientConnInterface) TcFullSigMsgHandleClient {
	return &tcFullSigMsgHandleClient{cc}
}

func (c *tcFullSigMsgHandleClient) TcFullSigMsgReceive(ctx context.Context, in *TcFullSigMsg, opts ...grpc.CallOption) (*TcFullSigMsgResponse, error) {
	out := new(TcFullSigMsgResponse)
	err := c.cc.Invoke(ctx, "/tcFullSigMsgpb.TcFullSigMsgHandle/TcFullSigMsgReceive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TcFullSigMsgHandleServer is the server API for TcFullSigMsgHandle service.
// All implementations must embed UnimplementedTcFullSigMsgHandleServer
// for forward compatibility
type TcFullSigMsgHandleServer interface {
	// Handles a received tcFullSigMsg message
	TcFullSigMsgReceive(context.Context, *TcFullSigMsg) (*TcFullSigMsgResponse, error)
	mustEmbedUnimplementedTcFullSigMsgHandleServer()
}

// UnimplementedTcFullSigMsgHandleServer must be embedded to have forward compatible implementations.
type UnimplementedTcFullSigMsgHandleServer struct {
}

func (UnimplementedTcFullSigMsgHandleServer) TcFullSigMsgReceive(context.Context, *TcFullSigMsg) (*TcFullSigMsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TcFullSigMsgReceive not implemented")
}
func (UnimplementedTcFullSigMsgHandleServer) mustEmbedUnimplementedTcFullSigMsgHandleServer() {}

// UnsafeTcFullSigMsgHandleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TcFullSigMsgHandleServer will
// result in compilation errors.
type UnsafeTcFullSigMsgHandleServer interface {
	mustEmbedUnimplementedTcFullSigMsgHandleServer()
}

func RegisterTcFullSigMsgHandleServer(s grpc.ServiceRegistrar, srv TcFullSigMsgHandleServer) {
	s.RegisterService(&TcFullSigMsgHandle_ServiceDesc, srv)
}

func _TcFullSigMsgHandle_TcFullSigMsgReceive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TcFullSigMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TcFullSigMsgHandleServer).TcFullSigMsgReceive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tcFullSigMsgpb.TcFullSigMsgHandle/TcFullSigMsgReceive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TcFullSigMsgHandleServer).TcFullSigMsgReceive(ctx, req.(*TcFullSigMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// TcFullSigMsgHandle_ServiceDesc is the grpc.ServiceDesc for TcFullSigMsgHandle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TcFullSigMsgHandle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tcFullSigMsgpb.TcFullSigMsgHandle",
	HandlerType: (*TcFullSigMsgHandleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TcFullSigMsgReceive",
			Handler:    _TcFullSigMsgHandle_TcFullSigMsgReceive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tcFullSigMsg.proto",
}
